name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn install

    - run: |
      touch .env
      echo uri=${{secrets.URI}}  >> .env
      echo emailid=${{secrets.EMAILID}}  >> .env
      echo emailpassword=${{secrets.EMAILPASSWORD}}  >> .env
      echo secret=${{secrets.SECRET}}  >> .env
      echo aessecret=${{secrets.AESSECRET}}  >> .env
      echo jwtsecret=${{secrets.JWTSECRET}} >> .env

    - run: yarn test
