name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn install
    - run: ./node_modules/.bin/cross-env uri='${{secrets.URI}}'
    - run: ./node_modules/.bin/cross-env-shell uri='${{secrets.URI}}'
    - run: ./node_modules/.bin/cross-env emailid=${{secrets.EMAILID}} 
    - run: ./node_modules/.bin/cross-env-shell emailid=${{secrets.EMAILID}} 
    - run: ./node_modules/.bin/cross-env emailpassword=${{secrets.EMAILPASSWORD}} 
    - run: ./node_modules/.bin/cross-env-shell emailpassword=${{secrets.EMAILPASSWORD}} 
    - run: ./node_modules/.bin/cross-env secret=${{secrets.SECRET}} 
    - run: ./node_modules/.bin/cross-env-shell secret=${{secrets.SECRET}} 
    - run: ./node_modules/.bin/cross-env aessecret=${{secrets.AESSECRET}} 
    - run: ./node_modules/.bin/cross-env-shell aessecret=${{secrets.AESSECRET}} 
    - run: ./node_modules/.bin/cross-env jwtsecret=${{secrets.JWTSECRET}} 
    - run: ./node_modules/.bin/cross-env-shell jwtsecret=${{secrets.JWTSECRET}} 

    - run: yarn test